minimal_mistakes_skin    : "default"  # 전체적인 블로그의 색감을 정하는 값입니다.
                           # "default" "air", "aqua", "contrast", "dark"
                           # "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"    # 블로그의 주요 언어입니다. 한국어로 보려고 ko-KR로 설정했습니다.
title                    : "KIMYOUGYEONG"  # 사이트 탭에서 보이는 이름입니다.
title_separator          : "-"
subtitle                 : "Protfolio"              # 화면 title 하단에 있는 소제목입니다.
name                     : "KIMYOUGYEONG"      # 화면 하단 영역의 이름입니다.
description              : "Front-End Developer KIMYOUGYEONG's Protfolio"   # 설명란입니다.
url                      : "https://tptkds.github.io" # 현재의 블로그 url 입니다.
baseurl                  : # 폴백(예기치 못한 오류)일 때 연결되는 url입니다.
repository               : "https://github.com/tptkds/tptkds.github.io/" # Github Repo url입니다.
teaser                   : # 폴백일 때 보일 이미지입니다. "assets/images/"로 연결됩니다.
logo                     : # 화면에 보여지는 logo 이미지입니다. "assets/images"로 세팅합니다.
masthead_title           : "Front-End Developer KIMYOUGYEONG's Protfolio"     # 화면 title 입니다.

# Site Author
author:
  name             : "KIMYOUGYEONG"                  # 이름 영역입니다.
  avatar           :  # 프로필 사진 경로입니다.
  bio              : "프론트 엔드 개발자 김유경의 포트폴리오입니다."
                     # biography의 약칭으로, 자기소개를 적으시면 됩니다.
                     # 줄바꿈은 <br>로 굵은 글씨는 **글씨** 로 표기해주세요. 
  location         : "Republic of Korea"            # 지역 입니다. 
  email            : # 이메일 주소입니다. (links에서 작성할 수 있기 때문에 생략하였습니다.)
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:tptkds12@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tptkds"
    - label: "Velog"
      icon: ""fa-solid fa-blog"
      url: "https://velog.io/@wlldone/posts"
